version: '3.9'

services:
  basis-member:
    build:
      context: ./docker/basis_member
      args:
        WORKDIR: '${WORKDIR:-/srv/basis_member}'
    container_name: php_basis_member
    volumes:
      - ./src/basis_member:/srv/basis_member
    networks:
      - app_network

  basis-admin:
    build:
      context: ./docker/basis_admin
      args:
        WORKDIR: '${WORKDIR:-/srv/basis_admin}'
    container_name: php_basis_admin
    volumes:
      - ./src/basis_admin:/srv/basis_admin
    networks:
      - app_network

  # mariadb:
  #   image: mariadb:11
  #   container_name: mariadb
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ${MARIADB_VOLUME}:/var/lib/mysql
  #   environment:
  #     MARIADB_ROOT_PASSWORD: ${DB_INFO_EDGE_PASSWORD}
  #   networks:
  #     - app_network

  # mysql:
  #   image: mysql:8.0.39
  #   container_name: mysql
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: local
  #     MYSQL_ALLOW_EMPTY_PASSWORD: yes

  nginx:
    container_name: nginx
    volumes:
      - ./src:/srv
    networks:
      - app_network

  cron:
    container_name: cron
    build:
      context: ./docker/cron
    volumes:
      - ./src:/srv
      - ./log/cron:/var/log/cron
    networks:
      - app_network

networks:
  app_network:

# volumes:
  # mysqldata:
  # mariadb_data_local:
  # mariadb_data_dev:
  # mariadb_data_prod:
